### ISSUE TITLE
Request: XFadeFilter implementation

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [tqk2811/FFmpegArgs#2]
Would like to request an XFadeFilter implementation

https://superuser.com/questions/1683630/timebase-error-while-giving-effect-using-ffmpeg

**Comment by tqk2811** [comment]
Not nuget now, but you can copy to your source

**Comment by Spartan-Hex-Shadow** [comment]
Thank you, please let me know when the update is in nuget.

**Comment by Spartan-Hex-Shadow** [comment]
> Not nuget now, but you can copy to your source
hi, are the changes in Nuget?

**Comment by tqk2811** [comment]
Just add this code to your project, use as extension.   
For nuget, wait until large change.   
I've been busy lately

**Comment by Spartan-Hex-Shadow** [comment]
> 

Not a problem at all. I can wait, thank you!

**Comment by Spartan-Hex-Shadow** [comment]
> Just add this code to your project, use as extension. For nuget, wait until large change. I've been busy lately

Not a problem at all, i can wait, thank you!

**Comment by tqk2811** [comment]
FFmpegArgs.Filters 1.4.3 is on nuget now

**Comment by Spartan-Hex-Shadow** [comment]
> FFmpegArgs.Filters 1.4.3 is on nuget now

Thank you!
