### ISSUE TITLE
Question: Concatenating multiple video files

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [tqk2811/FFmpegArgs#3]
What filter would i use to concatenate multiple videos files (no horizontal stacking)?
Basically, trying to replicate something like this 
"ffmpeg -i opening.mkv  -i episode.mkv  \
-filter_complex "[0:v] [1:v]  \
concat=n=2v=1:a=0[v]" \
-map "[v]" output.mkv"

**Comment by tqk2811** [comment]
```
List<ConcatGroup> list = new List<ConcatGroup>();
list.Add(new ConcatGroup(imageMap,audioMap));
var concatFilter = list.ConcatFilter();
```

**Comment by Spartan-Hex-Shadow** [comment]
> Add using namespace `using FFmpegArgs.Filters.MultimediaFilters;`
> 
> Video and audio
> 
> ```
> List<ConcatGroup> list = new List<ConcatGroup>();
> list.Add(new ConcatGroup(imageMap,audioMap));
> list.Add(new ConcatGroup(imageMap1,audioMap1));
> 
> var concatFilter = list.ConcatFilter();
> ```
> 
> Video only
> 
> ```
> List<ConcatGroup> list = new List<ConcatGroup>();
> list.Add(new ConcatGroup(imageMap));
> list.Add(new ConcatGroup(imageMap1));
> 
> var concatFilter = list.ConcatFilter();
> ```

Thanks for this example. How would we output this (lets assume its just videos only) concatenated video? The new ImageFileOutput takes in just a single ImageMap whereas the query methods for concatFilter either put out a basemap, an IEnumerable baseMap, or an IEnumerable of ImageMap or AudioMap.

**Comment by tqk2811** [comment]
`concatFilter.ImageMapsOut.First()` 
`concatFilter.AudioMapsOut.First()`

https://github.com/tqk2811/FFmpegArgs/blob/88d2efa6bc935e418629a3477b5c2cc792c14bba/FFmpegArgs.Filters/MultimediaFilters/ConcatFilter.cs#L22

**Comment by Spartan-Hex-Shadow** [comment]
> `concatFilter.ImageMapsOut.First()` `concatFilter.AudioMapsOut.First()`
> 
> https://github.com/tqk2811/FFmpegArgs/blob/88d2efa6bc935e418629a3477b5c2cc792c14bba/FFmpegArgs.Filters/MultimediaFilters/ConcatFilter.cs#L22

Perfect, thank you so much. Our team is truly appreciative of all the work you've done and plan on using this library extensively.
