### ISSUE TITLE
Request: Allow for conversion from one video (with audio) to another

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [tqk2811/FFmpegArgs#4]
I'm trying to convert from a mkv file (with audio) to a .webm file. I'm trying to replicate this argument 
"ffmpeg -i CombinedOutput.mkv -vcodec libvpx -acodec copy output.webm".
I can take in the .mkv file as a video input but the video output also requires an audio map argument. Is there another way to go about this that i'm not seeing?

**Comment by tqk2811** [comment]
```
var vmap = ffmpegArg.AddVideo(new VideoFileInput("CombinedOutput.mkv"));
ffmpegArg.AddOutput(
    new VideoFileOutput("output.webm", vmap.ImageMaps.First(), vmap.AudioMaps.First())
    .SetOption("-vcodec","libvpx")
    .SetOption("-acodec","copy"));
```
acodec default will be copy
