### ISSUE TITLE
Question: Execution of FFmpeg when binary is not in the project folder

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [tqk2811/FFmpegArgs#5]
We had a question.

We are planning to deploy a service that will run ffmpeg for video processing in an Alpine Linux Docker container. We don't want to have the FFmpeg.exe binary in the project itself. Rather, the DockerFile will run and install ffmpeg in that Alpine Linux Docker Container. Do we need to set the path to the ffmpeg.exe binary manually in Linux?

We have also set FFMpeg as a PATH variable in Windows 10 so that when we launch the command line console and enter "FFmpeg", it is able to tell us information about the ffmpeg binary. However, when we run the project locally in Windows 10, await ffmpeg.Render().ExecuteAsync(); call fails and says file not found. Do we have to set the path to ffmpeg.exe binary manually here as well?

**Comment by tqk2811** [comment]
Test project work well with PATH.   
https://github.com/tqk2811/FFmpegArgs/blob/88d2efa6bc935e418629a3477b5c2cc792c14bba/FFmpegArgs.Test/Render.cs#L5

Maybe your project not load/set environment?
Try `System.Environment.GetEnvironmentVariables()` to see what inside
