### ISSUE TITLE
Question: Concat Protocol

### ISSUE THREAD

**Issue by Spartan-Hex-Shadow** [tqk2811/FFmpegArgs#6]
Hi there,

Had a question. Is there a filter for using the Concat Protocol rather than the Concat Demuxer (which is what I think the current ConcatFilter class does)? 

Looking at Concat Protocol here: https://trac.ffmpeg.org/wiki/Concatenate

**Comment by tqk2811** [comment]
Not support and i not recommend use CP (concat protocol)

You can add as multi inputs and concat in filters.
___________________
If you still want CP, try this
`new VideoFileInput("concat:file1|file2")`

**Comment by tqk2811** [comment]
oh i was write it here https://github.com/tqk2811/FFmpegArgs/blob/2d8245b1b9d26c59ee9896cfcf2bfe0279d0f834/FFmpegArgs.Inputs/ImageFilesConcatInput.cs#L15

**Comment by Spartan-Hex-Shadow** [comment]
> oh i was write it here, you can custom yourself for video
> 
> https://github.com/tqk2811/FFmpegArgs/blob/2d8245b1b9d26c59ee9896cfcf2bfe0279d0f834/FFmpegArgs.Inputs/ImageFilesConcatInput.cs#L15

Does the Concat Protocol allow us to do this? From https://trac.ffmpeg.org/wiki/Concatenate

" using intermediate files
If you have MP4 files, these could be loss lessly concatenated by first transcoding them to MPEG-2 transport streams. With H.264 video and AAC audio, the following can be used:

ffmpeg -i input1.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate1.ts
ffmpeg -i input2.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts intermediate2.ts
ffmpeg -i "concat:intermediate1.ts|intermediate2.ts" -c copy -bsf:a aac_adtstoasc output.mp4 "

**Comment by tqk2811** [comment]
Yes, but I don't recommend it.

**Comment by Spartan-Hex-Shadow** [comment]
> Yes, but I don't recommend it.

Alright. But just for our own sake, if we had to do it, how would we go about doing it with the ConcatProtocol method?

**Comment by tqk2811** [comment]
Write same as   
 https://github.com/tqk2811/FFmpegArgs/blob/2d8245b1b9d26c59ee9896cfcf2bfe0279d0f834/FFmpegArgs.Inputs/ImageFilesConcatInput.cs#L15

**Comment by tqk2811** [comment]
`VideoFilesConcatInput.ConcatProtocol( filesList );`

**Comment by Spartan-Hex-Shadow** [comment]
> `VideoFilesConcatInput.ConcatProtocol( filesList );`

Awesome. This method uses temporary streams for the inputs and then concatenates those?

**Comment by tqk2811** [comment]
> > `VideoFilesConcatInput.ConcatProtocol( filesList );`
> 
> Awesome. This method uses temporary streams for the inputs and then concatenates those?

It same as `-i "concat:intermediate1.ts|intermediate2.ts"`
